### ISSUE TITLE
Git integration sometimes fails with github

### ISSUE THREAD

**Issue by rb2k** [whitesource/fs-agent#2]
This happens from time to time:
Extra info: I run this from a non-interactive script (stdin isn't the terminal)

```
[INFO] Connecting to SCM
[INFO] Cloning repository git@github.com:company/repo.git ...this may take a few minutes
Exception in thread "main" org.eclipse.jgit.errors.UnsupportedCredentialItem: ssh://git@github.com:22: org.eclipse.jgit.transport.CredentialItem$YesNoType:The authenticity of host 'github.com' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting?
    at org.whitesource.scm.PassphraseCredentialsProvider.get(PassphraseCredentialsProvider.java:118)
    at org.eclipse.jgit.transport.CredentialsProviderUserInfo.promptYesNo(CredentialsProviderUserInfo.java:124)
    at com.jcraft.jsch.Session.checkHost(Session.java:774)
    at com.jcraft.jsch.Session.connect(Session.java:342)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
    at org.whitesource.scm.GitConnector.cloneRepository(GitConnector.java:88)
    at org.whitesource.scm.ScmConnector.cloneRepository(ScmConnector.java:89)
    at org.whitesource.fs.WhitesourceFSAgent.getDependencyInfos(WhitesourceFSAgent.java:233)
    at org.whitesource.fs.WhitesourceFSAgent.createProjectInfo(WhitesourceFSAgent.java:215)
    at org.whitesource.fs.WhitesourceFSAgent.sendRequest(WhitesourceFSAgent.java:70)
    at org.whitesource.fs.Main.main(Main.java:51)
```

**Comment by tomshapira** [comment]
Which OS are you running from: Unix-based or Windows?
In any case it's an SSH issue, Unlike HTTPS, there is no chain of certificate authorities that establish trust for SSH. So you have to tell your computer that you trust github.com the first time you connect over SSH.

If you're using Unix, simply run:
```
ssh git@github.com
```

**Comment by rb2k** [comment]
This was running on OSX. I did manually connect before (and can do regular checkouts just fine), not quite sure what triggered this problem.
