### ISSUE TITLE
When extracting archives, folder to scan has to be absolute

### ISSUE THREAD

**Issue by slanglois** [whitesource/fs-agent#4]
This command works fine when archives are not extracted:

```
 java -jar whitesource-fs-agent-1.6.6.jar -c whitesource-fs-agent.config -d .
```

However, when adding the option to extract archives, it fails with the following error:

```
 Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1904)
    at org.whitesource.archiveReaders.ArchiveExtractor.extractArchives(ArchiveExtractor.java:97)
    at org.whitesource.fs.WhitesourceFSAgent.getDependencyInfos(WhitesourceFSAgent.java:250)
    at org.whitesource.fs.WhitesourceFSAgent.createProjectInfo(WhitesourceFSAgent.java:207)
    at org.whitesource.fs.WhitesourceFSAgent.sendRequest(WhitesourceFSAgent.java:76)
```

A workaround is to pass the folder with an absolute path:

```
      java -jar whitesource-fs-agent-1.6.6.jar -c whitesource-fs-agent.config -d D:\Releases\5.0.2.1
```

**Comment by annarozin** [comment]
Resolved
