### ISSUE TITLE
NPE running 1.8.5 tag

### ISSUE THREAD

**Issue by justincranford** [whitesource/fs-agent#7]
I get this error scanning a directory or file with the -d parameter.

```
java.lang.NullPointerException: null
        at org.whitesource.agent.FileSystemScanner.createDependencies(FileSystemScanner.java:126)
        at org.whitesource.fs.FileSystemAgent.getDependencyInfos(FileSystemAgent.java:156)
        at org.whitesource.fs.FileSystemAgent.createProjects(FileSystemAgent.java:80)
        at org.whitesource.agent.CommandLineAgent.sendRequest(CommandLineAgent.java:69)
        at org.whitesource.fs.Main.execute(Main.java:103)
        at org.whitesource.fs.Main.main(Main.java:49)
```

It might be due to an issue in DependencyInfoFactory.createDependencyInfo(). If line 112 evaluates to false, the call to dependency.setSystemPath() on line 119 is skipped. The file header SHA1 calculation is also skipped, but I think not calling setSystemPath() is root cause of NPE later on in FileSystemScanner.java:126.

```
            if (dependencyFile.length() <= MAX_FILE_SIZE) {
                File otherPlatformFile = createOtherPlatformFile(dependencyFile);
                if (otherPlatformFile != null) {
                    String otherPlatformSha1 = ChecksumUtils.calculateSHA1(otherPlatformFile);
                    dependency.setOtherPlatformSha1(otherPlatformSha1);
                }
                try {
                    dependency.setSystemPath(dependencyFile.getCanonicalPath());
                } catch (IOException e) {
                    dependency.setSystemPath(dependencyFile.getAbsolutePath());
                }
                deleteFile(otherPlatformFile);

                // calculate sha1 for file header and footer (for partial matching)
                if (partialSha1Match) {
                    ChecksumUtils.calculateHeaderAndFooterSha1(dependencyFile, dependency);
                }

                // removed finding license & copyrights in headers
            } else {
                logger.debug("File {} size is too big for scanning other platform sha1, skipping it.", dependencyFile.getName());
            }
```

**Comment by tomshapira** [comment]
Fixed in commit [4984a53](https://github.com/whitesource/fs-agent/commit/4984a53bc18154e9b1e16e6d0fc9d51c5b5fde52), set system path for all files )before checking file size)
