### ISSUE TITLE
Command line parsing bug in 1.8.8?

### ISSUE THREAD

**Issue by justincranford** [whitesource/fs-agent#9]
This command line works with 1.8.7 and fails with 1.8.8. It seems like a regression bug in 1.8.8. I am sticking with 1.8.7 for now.

Setup
```
#Open a Windows Git Bash console
cd /c/EclipseWS/UAT/whitesourceagent/ #Contains fs-agent jar and config
export PATH=/c/JDK/8-64/bin:$PATH
#Assume /r exists, and Windows R:\ is a 4095MB ram disk created by AMD Radeon Ramdisk. It is big enough to recursively extract content for most, but not all, archive scans.
```

fs-agent 1.8.8 fails
```
$ java -d64 -Xms1g -Xmx5g -Djava.io.tmpdir=/r -jar whitesource-fs-agent-1.8.8.jar -c whitesource-fs-agent.config -product "Staging-Sprint26" -project "myfile.tar" -d "/d/staging/myfile.tar"
[INFO] Starting Archive Extraction (may take a few minutes)
[WARN] Process encountered an error: {}Illegal char <:> at index 23: D:\staging\myfile.tar\D:\staging
java.nio.file.InvalidPathException: Illegal char <:> at index 23: D:\staging\myfile.tar\D:\staging
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.whitesource.agent.archive.ArchiveExtractor.handleArchiveFiles(ArchiveExtractor.java:249)
        at org.whitesource.agent.archive.ArchiveExtractor.extractArchives(ArchiveExtractor.java:184)
        at org.whitesource.agent.FileSystemScanner.createDependencies(FileSystemScanner.java:81)
        at org.whitesource.fs.FileSystemAgent.getDependencyInfos(FileSystemAgent.java:160)
        at org.whitesource.fs.FileSystemAgent.createProjects(FileSystemAgent.java:80)
        at org.whitesource.agent.CommandLineAgent.sendRequest(CommandLineAgent.java:71)
        at org.whitesource.fs.Main.execute(Main.java:107)
        at org.whitesource.fs.Main.main(Main.java:50)
```

fs-agent 1.8.7 succeeds
```
$ java -d64 -Xms1g -Xmx5g -Djava.io.tmpdir=/r -jar whitesource-fs-agent-1.8.7.jar -c whitesource-fs-agent.config -product "Staging-Sprint26" -project "myfile.tar" -d "/d/staging/myfile.tar"
[INFO] Starting Archive Extraction (may take a few minutes)
[INFO] Starting Analysis
[INFO] Scanning Directory [R:/\WhiteSource-ArchiveExtractor\20170927104631\myfile.tar, D:\staging\myfile.tar] for Matching Files (may take a few minutes)
[INFO] Total Files Found: 40
[INFO] Finished Analyzing Files
[INFO] Initializing WhiteSource Client
[INFO] Service URL is https://saas.whitesourcesoftware.com/agent
[INFO] Checking policies
[INFO] All dependencies conform with open source policies.
[INFO] Policies report generated successfully
[INFO] Sending Update
[INFO] Inventory update results for HCS
Newly created projects:
myfile.tar
No projects were updated.

Support Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

[INFO] Process finished with exit code SUCCESS (0)
```

**Comment by eugenhoro** [comment]
Hi Justin, thank you for bringing this to our attention. This issue should be fixed in v1.8.9
